// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC99gr5yacAjBlyWIXB7SSLgIkisMZNF28',
    appId: '1:12791516192:web:5b1658a99d56936cc28045',
    messagingSenderId: '12791516192',
    projectId: 'kaze-app-db8e3',
    authDomain: 'kaze-app-db8e3.firebaseapp.com',
    storageBucket: 'kaze-app-db8e3.appspot.com',
    measurementId: 'G-8TRV08R6Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7PlH3FV4R_kEWqSYm7CvKoB520b6GgRw',
    appId: '1:12791516192:android:ed36aa506363ea6dc28045',
    messagingSenderId: '12791516192',
    projectId: 'kaze-app-db8e3',
    storageBucket: 'kaze-app-db8e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyp5jpxvKKXgIEP4fFU-SICb6ZrF08tkg',
    appId: '1:12791516192:ios:38045e3ad0970dc4c28045',
    messagingSenderId: '12791516192',
    projectId: 'kaze-app-db8e3',
    storageBucket: 'kaze-app-db8e3.appspot.com',
    iosBundleId: 'com.example.kazeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC99gr5yacAjBlyWIXB7SSLgIkisMZNF28',
    appId: '1:12791516192:web:2ea6a9ab370a1f27c28045',
    messagingSenderId: '12791516192',
    projectId: 'kaze-app-db8e3',
    authDomain: 'kaze-app-db8e3.firebaseapp.com',
    storageBucket: 'kaze-app-db8e3.appspot.com',
    measurementId: 'G-QPMMDE6BM0',
  );
}
